### ISSUE TITLE
Pressing tab always fails

### ISSUE THREAD

**Issue by JasonMFry** [garaemon/vscode-emacs-tab#4]
Ignore. I think I hadn't saved `keybindings.json` or something :D

~If I press tab anywhere in a document, I get `Running the contributed command:'emacs-tab.reindentCurrentLine' failed.` and the tab key does nothing. I'm on macOS 10.13.3, VSCode 1.21.0, I have `vscode-emacs-tab` installed, and my keybindings.json is below.~

```
// Place your key bindings in this file to overwrite the defaults
[
  {
    "key": "ctrl+tab",
    "command": "workbench.action.nextEditor"
  },
  {
    "key": "alt+cmd+right",
    "command": "-workbench.action.nextEditor"
  },
  {
    "key": "ctrl+tab",
    "command": "-workbench.action.openNextRecentlyUsedEditorInGroup"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "workbench.action.previousEditor"
  },
  {
    "key": "shift+cmd+[",
    "command": "-workbench.action.previousEditor"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "-workbench.action.openPreviousRecentlyUsedEditorInGroup"
  },
  {
    "key": "tab",
    "command": "emacs-tab.reindentCurrentLine",
    "when": "editorTextFocus"
  }
]
```

Unfortunately that means I can't use this extension at all because it completely disables my tab key :(

**Comment by mgkuhn** [comment]
If your filed issue no longer applies, you should click the “Close issue” button for it on github.com.
